version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes
permissions:
  - object: /var/www/html
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/remove_existing_files.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 70
      runas: root
