version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/portfolio
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
