version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes
permissions:
  - object: /var/www/html
    owner: apache
    group: apache
hooks:
  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 70
      runas: root
