version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies
      - sudo apt-get update
      - |
        if ! sudo apt-get install -y curl; then
          echo "Dependency installation failed!"
          exit 1
        fi
  pre_build:
    commands:
      - echo Starting pre-build phase
      # Removed ./pre_build_script.sh as you don't have it
  build:
    commands:
      - echo Building the application
      - mvn clean install
  post_build:
    commands:
      - echo Post-build phase complete
      - ./post_build_script.sh
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
