version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      # Install dependencies or tools if needed
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=<your-ecr-repository-uri>  # Replace with your ECR URI
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Deploying to ECS...
      # You can use AWS CLI to update your ECS service or run the task
      - ecs_update=$(aws ecs update-service --cluster <your-cluster-name> --service <your-service-name> --force-new-deployment --region $AWS_DEFAULT_REGION)
      - echo "ECS update response: $ecs_update"
artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
