version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building the website..."
      - mkdir -p output
      - cp -r * output/
  post_build:
    commands:
      - echo "Build complete!"

artifacts:
  files:
    - '**/*'
  base-directory: output
